# as per https://hub.docker.com/_/rust
FROM rust:1.67 as builder
WORKDIR /app
COPY . .
RUN cargo install --path .

FROM alpine:3.20
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
CMD ["myapp"]
